blank_issues_enabled: false
contact_links:
  - name: 📚 Libraries and Frameworks Working Group
    url: https://erlef.org/wg/libs-and-frameworks
    about: Read about Libraries and Frameworks Working Group.

  - name: 💬 Ask on GitHub Discussion
    url: https://github.com/erlef/libs-and-frameworks/discussions
    about: The best place for asking general purpose questions.

  - name: 💬 Ask on Erlang Ecosystem Foundation Slack
    url: https://the-eef.slack.com/archives/C05DY7G9YAY
    about: Get in touch with the whole community.
